### ISSUE TITLE
Catkin Build failed

### ISSUE THREAD

**Issue by yoshida-e** [mmurooka/SMPLpp#1]
We trie to install on a Ubuntu 18.04 Machine, but we have got the following error.
It looks like the errros occur with QP collection.
We are afraid that the cause may not be the library itself, but would apprecaite if you make suggestions on how to solve this.

[221028-catkin-error.txt](https://github.com/mmurooka/SMPLpp/files/9899850/221028-catkin-error.txt)

**Comment by mmurooka** [comment]
Could you try the following commands?
```
cd <smplpp directory>
git fetch -a
git checkout fix-issue-1
git branch # Make sure the current branch is fix-issue-1
source /opt/ros/${ROS_DISTRO}/setup.bash
catkin build smplpp -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLIBTORCH_PATH=<absolute path to libtorch> -DENABLE_QLD=ON --catkin-make-args all tests
```

If it still fails, please try
```
source /home/yoshidalab/catkin_ws/src
catkin build smplpp -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLIBTORCH_PATH=<absolute path to libtorch> -DENABLE_QLD=ON --catkin-make-args all tests
```


I would like to know a little more about your environment, so could you please tell me the output of the following commands?
```
lsb_release -a

cmake --version

g++ --version

echo $ROS_DISTRO
```

**Comment by mmurooka** [comment]
If there are still errors, please share the output of catkin build with the following command. (Added `-vi` option)
```
catkin build smplpp -vi -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLIBTORCH_PATH=<absolute path to libtorch> -DENABLE_QLD=ON --catkin-make-args all tests
```

**Comment by yoshida-e** [comment]
Thank you very much for your reply.
Sorry, we still have errors, as attached.

The architecture information is the following:

> yoshidalab@yoshidalab-Precision-T5610:~/catkin_ws/build/smplpp$ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 18.04.6 LTS
> Release:    18.04
> Codename:   bionic
> yoshidalab@yoshidalab-Precision-T5610:~/catkin_ws/build/smplpp$ cmake --version
> cmake version 3.17.1
> CMake suite maintained and supported by Kitware (kitware.com/cmake).
> yoshidalab@yoshidalab-Precision-T5610:~/catkin_ws/build/smplpp$ g++ --version
> g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
> Copyright (C) 2017 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> yoshidalab@yoshidalab-Precision-T5610:~/catkin_ws/build/smplpp$ echo $ROS_DISTRO
> melodic
[221101-catkin-error.txt](https://github.com/mmurooka/SMPLpp/files/9909145/221101-catkin-error.txt)

**Comment by mmurooka** [comment]
Thanks, as far as I could see from the log file, there seemed to be no problem...

I don't know why many linking errors happen.
For example, the following linking error happens
```
[smplpp:make] /home/yoshidalab/catkin_ws/src/SMPLpp/node/node.cpp:660: `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)' に対する定義されていない参照です (Undefined reference)
```
although `/opt/ros/melodic/lib/librosconsole.so` is linked to the target.

Could you print the output of the following commands?
```
nm -D /opt/ros/melodic/lib/librosconsole.so | grep initializeLogLocation
```

**Comment by mmurooka** [comment]
Also, could you try putting `libtorch` outside of `catkin_ws`?

**Comment by yoshida-e** [comment]
Thank you for your kind instructions. Unfortunately the same result after moving libtorch.
The results are attached. Thank you again for your support.
[221101-catkin-error-2.txt](https://github.com/mmurooka/SMPLpp/files/9910349/221101-catkin-error-2.txt)

**Comment by mmurooka** [comment]
I investigated this issue directly with @yoshida-e and found that some versions of libtorch cause link errors in ROS.
We have confirmed that installing a slightly older libtorch (e.g. [this one](https://github.com/mmurooka/SMPLpp/blob/08d82871af8f8d020a750f77e54ab59f5f8dffe2/.github/workflows/ci.yaml#L140-L141)) instead of [the latest version](https://pytorch.org/cppdocs/installing.html#minimal-example
) of libtorch solves this issue.

Similar issues have been reported below and seem to be resolved by changing the libtorch version:
https://github.com/pytorch/pytorch/issues/22197
https://github.com/pytorch/pytorch/issues/49450
https://github.com/pytorch/pytorch/issues/60178
